exclude: '.git|.tox|.trash|lammps_wrapper'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: mpinterfaces_setup.py

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev:  v2.31.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.9b0]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py36-plus]
      - id: nbqa-isort
      - id: nbqa-flake8
        args: [--ignore=E402]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort, flake8-builtins, flake8-docstrings] # [flake8-isort, flake8-docstrings]
        exclude:  ^seibuilder/mpinterfaces/
