name: venv_sei
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ase=3.22.1
  - jupyterlab=4.0.7
  - matplotlib=3.7.3
  - numpy=1.24.4
  - scikit-learn~=0.22.2.post1
  - scipy~=1.5.2
  - pip:
      - nglview==3.0.8
      - pymatgen==2023.8.10