name: venv_sei
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ase=3.22.1
  - jupyter=1.0.0
  - jupyterlab=3.3.2
  - matplotlib=3.5.1
  - numpy=1.22.3
  - scikit-learn~=0.22.2.post1
  - scipy~=1.5.2
  - pip:
      - nglview==3.0.3
      - pymatgen==2020.12.18
